Repository DSM-DanMuZi/dsm-danmuzi-frontend, pull requests merged in 2023-02, with the labels that each got.

#4 [#3] 스터디 게시물 컴포넌트 제작
  components/common/study/index.tsx
Labels: 퍼블리싱

#8 [#7] 버튼 스타일 컴포넌트
  styles/button.tsx
Labels: 퍼블리싱

#6 [#4] 추천 인강 컴포넌트 퍼블리싱
  components/common/recommend/designer/index.tsx
  components/common/recommend/developer/index.tsx
  components/common/recommend/lecture/index.tsx
Labels: 퍼블리싱

#15 fix: prettier
  components/common/recommend/book/index.tsx
  components/common/recommend/designer/index.tsx
  components/common/recommend/lecture/index.tsx
Labels: refactor

#16 feat: study rank components
  components/common/study/rank/index.tsx
Labels: refactor, 퍼블리싱
